# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170911_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
