# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comment_edited_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='objects_count',
            field=models.IntegerField(default=0),
        ),
    ]
